[package]
name = "exa"
version = "0.3.0"
authors = [ "ogham@bsago.me" ]

[[bin]]
name = "exa"

[dependencies]
ansi_term = "0.5.0"
bitflags = "0.1"
datetime = "0.4.1"
getopts = "0.2.1"
libc = "*"
locale = "0.1.2"
natord = "1.0.7"
num_cpus = "*"
number_prefix = "0.2.3"
scoped_threadpool = "*"
term_grid = "*"
unicode-width = "*"
users = "0.4.0"

[features]
default = [ "git" ]
git = [ "git2" ]

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs.git"
optional = true
