[package]
name = "exa"
version = "0.1.0"
authors = [ "ogham@bsago.me" ]

[[bin]]
name = "exa"

[dependencies]
ansi_term = "0.4.5"
datetime = "0.1.2"
datetime_macros = "0.1.2"
getopts = "0.2.1"
natord = "1.0.7"
number_prefix = "0.2.3"
pad = "0.1.1"
users = "0.2.3"

[features]
default = [ "git" ]
git = [ "git2" ]

[dependencies.git2]
version = "0.1.13"
optional = true
