[package]
name = "exa"
version = "0.2.0"
authors = [ "ogham@bsago.me" ]

[[bin]]
name = "exa"

[dependencies]
ansi_term = "0.5.0"
datetime = "0.1.3"
getopts = "0.2.1"
locale = "0.1.2"
natord = "1.0.7"
num_cpus = "*"
number_prefix = "0.2.3"
pad = "0.1.1"
users = "0.3.1"
bitflags = "0.1"

[features]
default = [ "git" ]
git = [ "git2" ]

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs.git"
optional = true
