[package]
name = "exa"
version = "0.1.0"
authors = [ "ogham@bsago.me" ]

[[bin]]
name = "exa"

[dependencies.ansi_term]
git = "https://github.com/ogham/rust-ansi-term.git"

[dependencies.natord]
git = "https://github.com/lifthrasiir/rust-natord.git"

[dependencies.number_prefix]
git = "https://github.com/ogham/rust-number-prefix.git"

[dependencies.users]
git = "https://github.com/ogham/rust-users.git"
