# alternate date formats

[[cmd]]
name = "‘exa -l --time-style=long-iso’ produces a table using the long-iso date format"
shell = "exa -l --time-style=long-iso /testcases/dates"
stdout = { file = "outputs/dates_long_timestyle_longiso.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ 'long', 'time-style' ]

[[cmd]]
name = "‘exa -l --time-style=full-iso’ produces a table using the full-iso date format"
shell = "exa -l --time-style=full-iso /testcases/dates"
stdout = { file = "outputs/dates_long_timestyle_fulliso.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ 'long', 'time-style' ]

[[cmd]]
name = "‘exa -l --time-style=iso’ produces a table using the iso date format"
shell = "exa -l --time-style=iso /testcases/dates"
stdout = { file = "outputs/dates_long_timestyle_iso.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ 'long', 'time-style' ]


# locales

[[cmd]]
name = "‘exa -l’ using a locale with 4-character-long month abbreviations (‘ja_JP’) sizes the date column correctly"
shell = "exa -l /testcases/dates"
environment = { LC_ALL = "ja_JP.UTF-8", LANG = "ja_JP.UTF-8" }
stdout = { file = "outputs/dates_long_localejp.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ 'long', 'locales' ]

[[cmd]]
name = "‘exa -l’ using a locale with 5-character-long month abbreviations (‘fr_FR’) sizes the date column correctly"
shell = "exa -l /testcases/dates"
environment = { LC_ALL = "fr_FR.UTF-8", LANG = "fr_FR.UTF-8" }
stdout = { file = "outputs/dates_long_localefr.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ 'long', 'locales' ]
